package com.anda.muestras.model;

public enum Roles {
	ADMIN,
	QUIMICO_ANALISTA_LABORATORIO_MICROBIOLOGIA,
	QUIMICO_ANALISTA_MICROBIOLOGIA,
	QUIMICO_ANALISTA_MICROBIOLOGIA_RESIDUAL,
	MUESTREADOR,
	
}
